pipeline {
	agent {
		label 'master'
	}

	stages {
		stage('clone_pipeline-test') {
			steps {
				checkout([
					$class: 'GitSCM', 
					branches: [[name: '*/master']],
					doGenerateSubmoduleConfigurations: false,
					extensions: [[$class: 'LocalBranch', localBranch: 'master'], 
					[$class: 'CleanBeforeCheckout'], 
					[$class: 'RelativeTargetDirectory', relativeTargetDir: 'heatstack']],
					submoduleCfg: [], 
					userRemoteConfigs: [[credentialsId: '2e5f717b-82f6-4526-a358-42e77b16c6d5',url: 'https://review.corestack.in/heatstack']]
					])
			}
		}
	}
}
