pipeline {
	agent {
		label 'master'
	}

	stages {
		stage('clone_pipeline-test') {
			steps {
				branch: 'master',
				url: 'https://review.corestack.in/a/pipeline-test'
				credentialsId: '2e5f717b-82f6-4526-a358-42e77b16c6d5'
			}
		}
	}
}
